// Copyright 2021 Kovalev Ruslan
#ifndef MODULES_TASK_2_KOVALEV_R_RING_TOPOLOGY_KOVALEV_R_RING_TOPOLOGY_H_
#define MODULES_TASK_2_KOVALEV_R_RING_TOPOLOGY_KOVALEV_R_RING_TOPOLOGY_H_
#include <mpi.h>

MPI_Comm getRingTopology(const MPI_Comm comm);

#endif  // MODULES_TASK_2_KOVALEV_R_RING_TOPOLOGY_KOVALEV_R_RING_TOPOLOGY_H_
